<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: jcg23jordi002
 * Date: Tue, 02 Jan 2018 18:24:49 +0000
 */

$conf['title'] = 'WikiProgramariLliure';
$conf['template'] = 'bootstrap3';
$conf['license'] = 'cc-by-nc';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';

// end auto-generated content
