<?php
/**
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by install script
 * Date: Thu, 30 Nov 2017 14:40:58 +0000
 */
$conf['title'] = 'WikiProgramariLliure';
$conf['lang'] = 'en';
$conf['license'] = 'cc-by-nc';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
